# Knicks in Six — 01 · Data Gathering

Goal: predict the likelihood of the Knicks winning their **next game, game 6, and game 7** of the Finals with a **series-aware** model.

Project decisions:

| Decision | Choice |
|---|---|
| Live data | `nba_api` (stats.nba.com), snapshot-cached to `data/cache/*.parquet` |
| Historical data | Manually downloaded Kaggle dumps in `data/raw/` (no Kaggle API) |
| Scope | Playoffs **1980–present**, team + player level, season ids kept for era normalization |
| Model (later) | Series-aware: series score, elimination flag, rest days, home court |
| Storage | Parquet, fetch-if-missing; API failures fall back to last snapshot |

This notebook only **gathers and inventories** data. Feature engineering and modeling come in later notebooks. Reusable fetch/cache logic lives in `src/data.py`.

In [4]:
%load_ext autoreload
%autoreload 2

import pandas as pd

from src import data

pd.set_option("display.max_columns", 40)
print(f"Season: {data.CURRENT_SEASON} | Knicks team id: {data.KNICKS_ID}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Season: 2025-26 | Knicks team id: 1610612752

## 1. Live data (`nba_api`)

Current-season team strength tables. Each call writes a parquet snapshot to `data/cache/`; pass `refresh=True` to force a refetch (e.g. after a game is played).

In [5]:
team_adv = data.fetch_team_stats(season_type="Regular Season", measure="Advanced")
team_base = data.fetch_team_stats(season_type="Regular Season", measure="Base")
playoff_adv = data.fetch_team_stats(season_type="Playoffs", measure="Advanced")

cols = ["TEAM_NAME", "W", "L", "OFF_RATING", "DEF_RATING", "NET_RATING", "PACE"]
team_adv[cols].sort_values("NET_RATING", ascending=False).head(10)

                 TEAM_NAME   W   L  OFF_RATING  DEF_RATING  NET_RATING    PACE
20   Oklahoma City Thunder  64  18       117.6       106.5        11.1  100.37
26       San Antonio Spurs  62  20       118.7       110.4         8.4  100.72
8          Detroit Pistons  60  22       117.3       108.9         8.4   99.88
1           Boston Celtics  56  26       120.0       111.7         8.3   95.58
19         New York Knicks  53  29       118.7       112.3         6.4   97.71
10         Houston Rockets  52  30       117.5       112.1         5.4   96.98
7           Denver Nuggets  54  28       121.2       116.0         5.2   99.49
3        Charlotte Hornets  44  38       118.4       113.5         4.9   97.59
5      Cleveland Cavaliers  52  30       118.3       114.1         4.1  100.70
17  Minnesota Timberwolves  49  33       115.6       112.5         3.1  101.50

In [6]:
playoff_log = data.fetch_league_game_log(season_type="Playoffs")
season_log = data.fetch_league_game_log(season_type="Regular Season")

print(f"Playoff team-games: {len(playoff_log)} | Regular-season team-games: {len(season_log)}")

nyk_playoffs = playoff_log[playoff_log["TEAM_ID"] == data.KNICKS_ID]
nyk_playoffs[["GAME_DATE", "MATCHUP", "WL", "PTS", "PLUS_MINUS"]].tail(8)

Playoff team-games: 168 | Regular-season team-games: 2460

      GAME_DATE      MATCHUP WL  PTS  PLUS_MINUS
140  2026-05-19  NYK vs. CLE  W  115        11.0
144  2026-05-21  NYK vs. CLE  W  109        16.0
148  2026-05-23    NYK @ CLE  W  121        13.0
152  2026-05-25    NYK @ CLE  W  130        37.0
160  2026-06-03    NYK @ SAS  W  105        10.0
163  2026-06-05    NYK @ SAS  W  105         1.0
164  2026-06-08  NYK vs. SAS  L  111        -4.0
167  2026-06-10  NYK vs. SAS  W  107         1.0

### Current Finals series state

Derived from the playoff game log: opponent, series score, and who hosts the next game / game 6 / game 7 under the 2-2-1-1-1 format. This dict is the live input the model will score against.

In [7]:
state = data.knicks_series_state()
for k, v in state.items():
    print(f"{k:>22}: {v}")

                season: 2025-26
              opponent: SAS
         series_record: 3-1
                  wins: 3
                losses: 1
          games_played: 4
         next_game_num: 5
        knicks_has_hca: False
      knicks_home_next: False
        knicks_home_g6: True
        knicks_home_g7: False
 elimination_game_next: True
        last_game_date: 2026-06-10

## 2. Historical data (manual Kaggle dumps)

Training data for the series-aware model: playoff games and player box scores, **1980–present**. Kaggle API is intentionally not used — download the files yourself and drop them in `data/raw/` (see `data/raw/README.md` for the shopping list and candidate datasets).

The cell below inventories whatever is there and previews each file so we can map schemas in the feature-engineering step.

In [8]:
raw_files = data.list_raw_files()

if not raw_files:
    print("No raw files yet — see data/raw/README.md for what to download.")
for path in raw_files:
    head, n_rows = data.preview_raw(path)
    rel = path.relative_to(data.RAW_DIR)
    size_mb = path.stat().st_size / 1e6
    print(f"\n=== {rel} — {n_rows:,} rows x {head.shape[1]} cols ({size_mb:,.0f} MB) ===")
    print("columns:", list(head.columns)[:25])
    display(head)

=== nba_dataset/Advanced.csv — 33,339 rows x 30 cols (5 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp', 'per', 'ts_percent', 'x3p_ar', 'f_tr', 'orb_percent', 'drb_percent', 'trb_percent', 'ast_percent', 'stl_percent', 'blk_percent', 'tov_percent', 'usg_percent', 'ows', 'dws', 'ws']

,season,lg,player,player_id,age,team,pos,g,gs,mp,per,ts_percent,x3p_ar,f_tr,orb_percent,drb_percent,trb_percent,ast_percent,stl_percent,blk_percent,tov_percent,usg_percent,ows,dws,ws,ws_48,obpm,dbpm,bpm,vorp
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,16.2,0.558,0.162,0.232,11.0,20.8,15.8,8.5,1.8,2.6,9.0,17.6,1.8,1.2,2.9,0.081,-0.5,-1.1,-1.6,0.2
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,15.8,0.535,0.000,0.583,22.3,19.6,21.0,8.3,1.5,2.5,16.7,12.1,1.1,1.0,2.1,0.141,-0.1,-0.3,-0.5,0.3
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,18.7,0.551,0.349,0.369,6.5,25.7,16.1,14.1,1.7,1.8,8.3,25.0,2.8,3.6,6.4,0.129,1.5,0.4,2.0,2.4

=== nba_dataset/All-Star Selections.csv — 2,058 rows x 6 cols (0 MB) ===
columns: ['player', 'player_id', 'team', 'season', 'lg', 'replaced']

            player  player_id        team  season   lg  replaced
0   Scottie Barnes  barnesc01  Team Stars    2026  NBA     False
1     Devin Booker  bookede01  Team Stars    2026  NBA     False
2  Cade Cunningham  cunnica01  Team Stars    2026  NBA     False

=== nba_dataset/Draft Pick History.csv — 8,383 rows x 8 cols (0 MB) ===
columns: ['season', 'lg', 'overall_pick', 'round', 'tm', 'player', 'player_id', 'college']

,season,lg,overall_pick,round,tm,player,player_id,college
0,2025,NBA,1,1,DAL,Cooper Flagg,flaggco01,Duke
1,2025,NBA,2,1,SAS,Dylan Harper,harpedy01,Rutgers University
2,2025,NBA,3,1,PHI,VJ Edgecombe,edgecvj01,Baylor

=== nba_dataset/End of Season Teams (Voting).csv — 4,484 rows x 14 cols (0 MB) ===
columns: ['season', 'lg', 'type', 'number_tm', 'position', 'player', 'player_id', 'age', 'pts_won', 'pts_max', 'share', 'x1st_tm', 'x2nd_tm', 'x3rd_tm']

,season,lg,type,number_tm,position,player,player_id,age,pts_won,pts_max,share,x1st_tm,x2nd_tm,x3rd_tm
0,2025,nba,all_defense,1st,F,Evan Mobley,mobleev01,23,199,200,0.995,NaN,NaN,NaN
1,2025,nba,all_defense,1st,G,Dyson Daniels,daniedy01,21,191,200,0.955,NaN,NaN,NaN
2,2025,nba,all_defense,1st,F,Luguentz Dort,dortlu01,25,180,200,0.900,NaN,NaN,NaN

=== nba_dataset/End of Season Teams.csv — 2,222 rows x 7 cols (0 MB) ===
columns: ['season', 'lg', 'type', 'number_tm', 'player', 'player_id', 'position']

   season   lg         type number_tm          player  player_id  position
0    2025  NBA  All-Defense       1st   Dyson Daniels  daniedy01       NaN
1    2025  NBA  All-Defense       1st   Luguentz Dort   dortlu01       NaN
2    2025  NBA  All-Defense       1st  Draymond Green  greendr01       NaN

=== nba_dataset/Opponent Stats Per 100 Poss.csv — 1,462 rows x 28 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'opp_fg_per_100_poss', 'opp_fga_per_100_poss', 'opp_fg_percent', 'opp_x3p_per_100_poss', 'opp_x3pa_per_100_poss', 'opp_x3p_percent', 'opp_x2p_per_100_poss', 'opp_x2pa_per_100_poss', 'opp_x2p_percent', 'opp_ft_per_100_poss', 'opp_fta_per_100_poss', 'opp_ft_percent', 'opp_orb_per_100_poss', 'opp_drb_per_100_poss', 'opp_trb_per_100_poss', 'opp_ast_per_100_poss', 'opp_stl_per_100_poss', 'opp_blk_per_100_poss']

,season,lg,team,abbreviation,playoffs,g,mp,opp_fg_per_100_poss,opp_fga_per_100_poss,opp_fg_percent,opp_x3p_per_100_poss,opp_x3pa_per_100_poss,opp_x3p_percent,opp_x2p_per_100_poss,opp_x2pa_per_100_poss,opp_x2p_percent,opp_ft_per_100_poss,opp_fta_per_100_poss,opp_ft_percent,opp_orb_per_100_poss,opp_drb_per_100_poss,opp_trb_per_100_poss,opp_ast_per_100_poss,opp_stl_per_100_poss,opp_blk_per_100_poss,opp_tov_per_100_poss,opp_pf_per_100_poss,opp_pts_per_100_poss
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,41.5,87.7,0.474,12.6,35.5,0.355,28.9,52.1,0.554,18.1,22.8,0.794,10.9,33.4,44.3,26.1,8.3,4.8,15.7,18.1,113.7
1,2026,NBA,Boston Celtics,BOS,False,82,19730,40.3,91.3,0.442,14.7,41.1,0.358,25.6,50.1,0.511,17.3,22.3,0.775,11.4,31.9,43.3,26.0,6.5,4.3,13.1,19.3,112.7
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,43.3,87.0,0.497,12.9,33.7,0.381,30.4,53.2,0.571,19.6,25.3,0.775,10.4,34.3,44.7,28.2,9.4,5.5,14.9,20.0,119.0

=== nba_dataset/Opponent Stats Per Game.csv — 1,907 rows x 28 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp_per_game', 'opp_fg_per_game', 'opp_fga_per_game', 'opp_fg_percent', 'opp_x3p_per_game', 'opp_x3pa_per_game', 'opp_x3p_percent', 'opp_x2p_per_game', 'opp_x2pa_per_game', 'opp_x2p_percent', 'opp_ft_per_game', 'opp_fta_per_game', 'opp_ft_percent', 'opp_orb_per_game', 'opp_drb_per_game', 'opp_trb_per_game', 'opp_ast_per_game', 'opp_stl_per_game', 'opp_blk_per_game']

,season,lg,team,abbreviation,playoffs,g,mp_per_game,opp_fg_per_game,opp_fga_per_game,opp_fg_percent,opp_x3p_per_game,opp_x3pa_per_game,opp_x3p_percent,opp_x2p_per_game,opp_x2pa_per_game,opp_x2p_percent,opp_ft_per_game,opp_fta_per_game,opp_ft_percent,opp_orb_per_game,opp_drb_per_game,opp_trb_per_game,opp_ast_per_game,opp_stl_per_game,opp_blk_per_game,opp_tov_per_game,opp_pf_per_game,opp_pts_per_game
0,2026,NBA,Atlanta Hawks,ATL,False,82,240.9,42.4,89.4,0.474,12.9,36.3,0.355,29.5,53.2,0.554,18.5,23.2,0.794,11.1,34.1,45.2,26.6,8.5,4.9,16.1,18.5,116.0
1,2026,NBA,Boston Celtics,BOS,False,82,240.6,38.4,86.8,0.442,14.0,39.1,0.358,24.3,47.6,0.511,16.4,21.2,0.775,10.9,30.4,41.2,24.7,6.2,4.1,12.4,18.4,107.2
2,2026,NBA,Brooklyn Nets,BRK,False,82,240.9,42.2,84.7,0.497,12.5,32.9,0.381,29.6,51.9,0.571,19.1,24.6,0.775,10.2,33.4,43.6,27.5,9.1,5.3,14.5,19.5,115.9

=== nba_dataset/Opponent Totals.csv — 1,907 rows x 28 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'opp_fg', 'opp_fga', 'opp_fg_percent', 'opp_x3p', 'opp_x3pa', 'opp_x3p_percent', 'opp_x2p', 'opp_x2pa', 'opp_x2p_percent', 'opp_ft', 'opp_fta', 'opp_ft_percent', 'opp_orb', 'opp_drb', 'opp_trb', 'opp_ast', 'opp_stl', 'opp_blk']

,season,lg,team,abbreviation,playoffs,g,mp,opp_fg,opp_fga,opp_fg_percent,opp_x3p,opp_x3pa,opp_x3p_percent,opp_x2p,opp_x2pa,opp_x2p_percent,opp_ft,opp_fta,opp_ft_percent,opp_orb,opp_drb,opp_trb,opp_ast,opp_stl,opp_blk,opp_tov,opp_pf,opp_pts
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,3473,7334,0.474,1056,2973,0.355,2417,4361,0.554,1514,1906,0.794,914,2796,3710,2185,695,402,1317,1515,9516
1,2026,NBA,Boston Celtics,BOS,False,82,19730,3145,7115,0.442,1149,3208,0.358,1996,3907,0.511,1348,1740,0.775,890,2489,3379,2029,505,339,1018,1508,8787
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,3457,6949,0.497,1027,2696,0.381,2430,4253,0.571,1564,2018,0.775,834,2739,3573,2254,750,436,1189,1595,9505

=== nba_dataset/Per 100 Poss.csv — 27,692 rows x 34 cols (4 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp', 'fg_per_100_poss', 'fga_per_100_poss', 'fg_percent', 'x3p_per_100_poss', 'x3pa_per_100_poss', 'x3p_percent', 'x2p_per_100_poss', 'x2pa_per_100_poss', 'x2p_percent', 'e_fg_percent', 'ft_per_100_poss', 'fta_per_100_poss', 'ft_percent', 'orb_per_100_poss', 'drb_per_100_poss']

,season,lg,player,player_id,age,team,pos,g,gs,mp,fg_per_100_poss,fga_per_100_poss,fg_percent,x3p_per_100_poss,x3pa_per_100_poss,x3p_percent,x2p_per_100_poss,x2pa_per_100_poss,x2p_percent,e_fg_percent,ft_per_100_poss,fta_per_100_poss,ft_percent,orb_per_100_poss,drb_per_100_poss,trb_per_100_poss,ast_per_100_poss,stl_per_100_poss,blk_per_100_poss,tov_per_100_poss,pf_per_100_poss,pts_per_100_poss,o_rtg,d_rtg
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,8.8,16.6,0.528,0.7,2.7,0.278,8.0,13.9,0.577,0.551,2.1,3.9,0.554,4.9,8.7,13.6,2.8,1.8,1.4,1.8,3.4,20.4,117,119
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,4.8,9.5,0.504,0.0,0.0,NaN,4.8,9.5,0.504,0.504,3.2,5.5,0.580,9.9,9.0,18.9,3.3,1.5,1.4,2.4,3.8,12.8,125,112
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,9.9,22.5,0.442,2.5,7.8,0.318,7.4,14.6,0.509,0.497,6.5,8.3,0.778,2.9,11.4,14.4,4.6,1.7,1.0,2.4,2.4,28.8,115,111

=== nba_dataset/Per 36 Minutes.csv — 32,256 rows x 32 cols (5 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp', 'fg_per_36_min', 'fga_per_36_min', 'fg_percent', 'x3p_per_36_min', 'x3pa_per_36_min', 'x3p_percent', 'x2p_per_36_min', 'x2pa_per_36_min', 'x2p_percent', 'e_fg_percent', 'ft_per_36_min', 'fta_per_36_min', 'ft_percent', 'orb_per_36_min', 'drb_per_36_min']

,season,lg,player,player_id,age,team,pos,g,gs,mp,fg_per_36_min,fga_per_36_min,fg_percent,x3p_per_36_min,x3pa_per_36_min,x3p_percent,x2p_per_36_min,x2pa_per_36_min,x2p_percent,e_fg_percent,ft_per_36_min,fta_per_36_min,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,6.5,12.3,0.528,0.6,2.0,0.278,6.0,10.3,0.577,0.551,1.6,2.9,0.554,3.7,6.5,10.2,2.1,1.3,1.0,1.3,2.5,15.2
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,3.5,6.9,0.504,0.0,0.0,NaN,3.5,6.9,0.504,0.504,2.3,4.0,0.580,7.2,6.5,13.6,2.4,1.1,1.0,1.7,2.7,9.2
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,7.7,17.4,0.442,1.9,6.1,0.318,5.8,11.3,0.509,0.497,5.0,6.4,0.778,2.3,8.9,11.1,3.5,1.3,0.7,1.8,1.9,22.3

=== nba_dataset/Player Award Shares.csv — 3,465 rows x 10 cols (0 MB) ===
columns: ['season', 'award', 'player', 'player_id', 'age', 'first', 'pts_won', 'pts_max', 'share', 'winner']

,season,award,player,player_id,age,first,pts_won,pts_max,share,winner
0,2025,nba clutch_poy,Jalen Brunson,brunsja01,28,70,426,500,0.852,True
1,2025,nba clutch_poy,Nikola Jokić,jokicni01,29,26,312,500,0.624,False
2,2025,nba clutch_poy,Anthony Edwards,edwaran01,23,2,47,500,0.094,False

=== nba_dataset/Player Career Info.csv — 5,416 rows x 11 cols (1 MB) ===
columns: ['player', 'player_id', 'pos', 'ht_in_in', 'wt', 'birth_date', 'colleges', 'from', 'to', 'debut', 'hof']

,player,player_id,pos,ht_in_in,wt,birth_date,colleges,from,to,debut,hof
0,Hank Biasatti,biasaha01,G,71,175,1922-01-14,Assumption University,1947,1947,1946-11-01T00:00:00Z,False
1,Tommy Byrnes,byrneto01,F-G,75,175,1923-02-19,Seton Hall,1947,1951,1946-11-01T00:00:00Z,False
2,Bob Fitzgerald,fitzgbo01,F-C,77,190,1923-03-14,Seton Hall,1947,1949,1946-11-01T00:00:00Z,False

=== nba_dataset/Player Per Game.csv — 33,339 rows x 32 cols (5 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp_per_game', 'fg_per_game', 'fga_per_game', 'fg_percent', 'x3p_per_game', 'x3pa_per_game', 'x3p_percent', 'x2p_per_game', 'x2pa_per_game', 'x2p_percent', 'e_fg_percent', 'ft_per_game', 'fta_per_game', 'ft_percent', 'orb_per_game', 'drb_per_game']

,season,lg,player,player_id,age,team,pos,g,gs,mp_per_game,fg_per_game,fga_per_game,fg_percent,x3p_per_game,x3pa_per_game,x3p_percent,x2p_per_game,x2pa_per_game,x2p_percent,e_fg_percent,ft_per_game,fta_per_game,ft_percent,orb_per_game,drb_per_game,trb_per_game,ast_per_game,stl_per_game,blk_per_game,tov_per_game,pf_per_game,pts_per_game
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,23.9,4.3,8.2,0.528,0.4,1.3,0.278,4.0,6.9,0.577,0.551,1.1,1.9,0.554,2.4,4.3,6.7,1.4,0.9,0.7,0.9,1.7,10.1
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,22.8,2.2,4.3,0.504,0.0,0.0,NaN,2.2,4.3,0.504,0.504,1.5,2.5,0.580,4.5,4.1,8.6,1.5,0.7,0.6,1.1,1.7,5.8
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,32.4,6.9,15.7,0.442,1.7,5.5,0.318,5.2,10.2,0.509,0.497,4.5,5.8,0.778,2.0,8.0,10.0,3.2,1.2,0.7,1.6,1.7,20.1

=== nba_dataset/Player Play By Play.csv — 18,254 rows x 26 cols (2 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp', 'pg_percent', 'sg_percent', 'sf_percent', 'pf_percent', 'c_percent', 'on_court_plus_minus_per_100_poss', 'net_plus_minus_per_100_poss', 'bad_pass_turnover', 'lost_ball_turnover', 'shooting_foul_committed', 'offensive_foul_committed', 'shooting_foul_drawn', 'offensive_foul_drawn', 'points_generated_by_assists', 'and1']

,season,lg,player,player_id,age,team,pos,g,gs,mp,pg_percent,sg_percent,sf_percent,pf_percent,c_percent,on_court_plus_minus_per_100_poss,net_plus_minus_per_100_poss,bad_pass_turnover,lost_ball_turnover,shooting_foul_committed,offensive_foul_committed,shooting_foul_drawn,offensive_foul_drawn,points_generated_by_assists,and1,fga_blocked
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,0,0,0,83,17,-7.2,5.4,16,31,77,8,70,6,237,15,43
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,0,0,0,0,100,11.3,7.4,14,8,22,9,30,1,107,3,9
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,0,0,0,21,79,6.4,9.5,46,52,57,9,188,4,574,39,37

=== nba_dataset/Player Season Info.csv — 33,339 rows x 8 cols (1 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'experience']

   season   lg          player  player_id  age team  pos  experience
0    1947  BAA  John Abramovic  abramjo01   27  PIT  NaN           1
1    1947  BAA   Chet Aubuchon  aubucch01   30  DTF  NaN           1
2    1947  BAA      Norm Baker  bakerno01   23  CHS  NaN           1

=== nba_dataset/Player Shooting.csv — 18,254 rows x 32 cols (3 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp', 'fg_percent', 'avg_dist_fga', 'percent_fga_from_x2p_range', 'percent_fga_from_x0_3_range', 'percent_fga_from_x3_10_range', 'percent_fga_from_x10_16_range', 'percent_fga_from_x16_3p_range', 'percent_fga_from_x3p_range', 'fg_percent_from_x2p_range', 'fg_percent_from_x0_3_range', 'fg_percent_from_x3_10_range', 'fg_percent_from_x10_16_range', 'fg_percent_from_x16_3p_range', 'fg_percent_from_x3p_range', 'percent_assisted_x2p_fg']

,season,lg,player,player_id,age,team,pos,g,gs,mp,fg_percent,avg_dist_fga,percent_fga_from_x2p_range,percent_fga_from_x0_3_range,percent_fga_from_x3_10_range,percent_fga_from_x10_16_range,percent_fga_from_x16_3p_range,percent_fga_from_x3p_range,fg_percent_from_x2p_range,fg_percent_from_x0_3_range,fg_percent_from_x3_10_range,fg_percent_from_x10_16_range,fg_percent_from_x16_3p_range,fg_percent_from_x3p_range,percent_assisted_x2p_fg,percent_assisted_x3p_fg,percent_dunks_of_fga,num_of_dunks,percent_corner_3s_of_3pa,corner_3_point_percent,num_heaves_attempted,num_heaves_made
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,0.528,7.8,0.838,0.371,0.395,0.064,0.007,0.162,0.577,0.707,0.513,0.289,0.000,0.278,0.543,1.000,0.135,68,0.412,0.25,0,0
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,0.504,2.6,1.000,0.655,0.309,0.036,0.000,0.000,0.504,0.582,0.349,0.400,NaN,NaN,0.514,NaN,0.129,13,NaN,NaN,0,0
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,0.442,13.3,0.651,0.205,0.252,0.148,0.045,0.349,0.509,0.685,0.450,0.426,0.308,0.318,0.612,0.961,0.079,81,0.313,0.32,0,0

=== nba_dataset/Player Totals.csv — 33,339 rows x 33 cols (4 MB) ===
columns: ['season', 'lg', 'player', 'player_id', 'age', 'team', 'pos', 'g', 'gs', 'mp', 'fg', 'fga', 'fg_percent', 'x3p', 'x3pa', 'x3p_percent', 'x2p', 'x2pa', 'x2p_percent', 'e_fg_percent', 'ft', 'fta', 'ft_percent', 'orb', 'drb']

,season,lg,player,player_id,age,team,pos,g,gs,mp,fg,fga,fg_percent,x3p,x3pa,x3p_percent,x2p,x2pa,x2p_percent,e_fg_percent,ft,fta,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts,trp_dbl
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,316,598,0.528,27,97,0.278,289,501,0.577,0.551,77,139,0.554,177,315,492,101,65,50,65,123,736,0
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,70,139,0.504,0,0,NaN,70,139,0.504,0.504,47,81,0.580,145,131,276,48,22,20,35,55,187,0
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,506,1145,0.442,127,400,0.318,379,745,0.509,0.497,329,423,0.778,149,583,732,232,86,49,120,122,1468,0

=== nba_dataset/Team Abbrev.csv — 1,818 rows x 5 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs']

   season   lg            team abbreviation  playoffs
0    2026  NBA   Atlanta Hawks          ATL     False
1    2026  NBA  Boston Celtics          BOS     False
2    2026  NBA   Brooklyn Nets          BRK     False

=== nba_dataset/Team Stats Per 100 Poss.csv — 1,462 rows x 28 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'fg_per_100_poss', 'fga_per_100_poss', 'fg_percent', 'x3p_per_100_poss', 'x3pa_per_100_poss', 'x3p_percent', 'x2p_per_100_poss', 'x2pa_per_100_poss', 'x2p_percent', 'ft_per_100_poss', 'fta_per_100_poss', 'ft_percent', 'orb_per_100_poss', 'drb_per_100_poss', 'trb_per_100_poss', 'ast_per_100_poss', 'stl_per_100_poss', 'blk_per_100_poss']

,season,lg,team,abbreviation,playoffs,g,mp,fg_per_100_poss,fga_per_100_poss,fg_percent,x3p_per_100_poss,x3pa_per_100_poss,x3p_percent,x2p_per_100_poss,x2pa_per_100_poss,x2p_percent,ft_per_100_poss,fta_per_100_poss,ft_percent,orb_per_100_poss,drb_per_100_poss,trb_per_100_poss,ast_per_100_poss,stl_per_100_poss,blk_per_100_poss,tov_per_100_poss,pf_per_100_poss,pts_per_100_poss
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,42.7,90.1,0.474,14.4,38.7,0.371,28.4,51.4,0.552,16.3,21.1,0.774,10.8,31.9,42.7,29.5,9.2,4.6,13.9,19.3,116.1
1,2026,NBA,Boston Celtics,BOS,False,82,19730,44.3,94.9,0.467,16.3,44.3,0.367,28.1,50.6,0.555,15.9,19.7,0.807,13.1,35.6,48.8,25.9,7.5,5.3,13.0,20.0,120.8
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,38.4,86.8,0.443,13.4,39.5,0.340,25.0,47.3,0.528,18.4,23.6,0.780,10.6,29.8,40.4,25.7,8.2,4.4,16.2,21.6,108.7

=== nba_dataset/Team Stats Per Game.csv — 1,907 rows x 28 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp_per_game', 'fg_per_game', 'fga_per_game', 'fg_percent', 'x3p_per_game', 'x3pa_per_game', 'x3p_percent', 'x2p_per_game', 'x2pa_per_game', 'x2p_percent', 'ft_per_game', 'fta_per_game', 'ft_percent', 'orb_per_game', 'drb_per_game', 'trb_per_game', 'ast_per_game', 'stl_per_game', 'blk_per_game']

,season,lg,team,abbreviation,playoffs,g,mp_per_game,fg_per_game,fga_per_game,fg_percent,x3p_per_game,x3pa_per_game,x3p_percent,x2p_per_game,x2pa_per_game,x2p_percent,ft_per_game,fta_per_game,ft_percent,orb_per_game,drb_per_game,trb_per_game,ast_per_game,stl_per_game,blk_per_game,tov_per_game,pf_per_game,pts_per_game
0,2026,NBA,Atlanta Hawks,ATL,False,82,240.9,43.6,92.0,0.474,14.6,39.5,0.371,29.0,52.5,0.552,16.6,21.5,0.774,11.0,32.6,43.5,30.1,9.4,4.7,14.2,19.7,118.5
1,2026,NBA,Boston Celtics,BOS,False,82,240.6,42.1,90.2,0.467,15.5,42.1,0.367,26.7,48.1,0.555,15.1,18.7,0.807,12.5,33.9,46.4,24.6,7.1,5.0,12.4,19.0,114.9
2,2026,NBA,Brooklyn Nets,BRK,False,82,240.9,37.5,84.5,0.443,13.1,38.4,0.340,24.4,46.1,0.528,17.9,23.0,0.780,10.3,29.0,39.3,25.0,8.0,4.3,15.8,21.1,105.9

=== nba_dataset/Team Summaries.csv — 1,907 rows x 31 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs', 'age', 'w', 'l', 'pw', 'pl', 'mov', 'sos', 'srs', 'o_rtg', 'd_rtg', 'n_rtg', 'pace', 'f_tr', 'x3p_ar', 'ts_percent', 'e_fg_percent', 'tov_percent', 'orb_percent', 'ft_fga', 'opp_e_fg_percent']

,season,lg,team,abbreviation,playoffs,age,w,l,pw,pl,mov,sos,srs,o_rtg,d_rtg,n_rtg,pace,f_tr,x3p_ar,ts_percent,e_fg_percent,tov_percent,orb_percent,ft_fga,opp_e_fg_percent,opp_tov_percent,drb_percent,opp_ft_fga,arena,attend,attend_g
0,2026,NBA,Atlanta Hawks,ATL,False,25.2,46,36,47,35,2.41,-0.03,2.38,116.1,113.7,2.4,101.7,0.234,0.429,0.584,0.554,12.3,24.4,0.181,0.546,13.9,74.5,0.206,State Farm Arena,670581,16356
1,2026,NBA,Boston Celtics,BOS,False,26.9,56,26,59,23,7.70,-0.33,7.37,120.8,112.7,8.1,94.8,0.207,0.467,0.583,0.553,11.2,29.2,0.167,0.523,11.4,75.7,0.189,TD Garden,785396,19156
2,2026,NBA,Brooklyn Nets,BRK,False,23.5,20,62,18,64,-9.99,0.29,-9.70,108.7,119.0,-10.3,97.1,0.272,0.455,0.559,0.520,14.3,23.6,0.212,0.571,13.2,74.0,0.225,Barclays Center,713896,17412

=== nba_dataset/Team Totals.csv — 1,907 rows x 28 cols (0 MB) ===
columns: ['season', 'lg', 'team', 'abbreviation', 'playoffs', 'g', 'mp', 'fg', 'fga', 'fg_percent', 'x3p', 'x3pa', 'x3p_percent', 'x2p', 'x2pa', 'x2p_percent', 'ft', 'fta', 'ft_percent', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk']

,season,lg,team,abbreviation,playoffs,g,mp,fg,fga,fg_percent,x3p,x3pa,x3p_percent,x2p,x2pa,x2p_percent,ft,fta,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,3575,7541,0.474,1201,3237,0.371,2374,4304,0.552,1363,1762,0.774,900,2670,3570,2471,768,384,1162,1612,9714
1,2026,NBA,Boston Celtics,BOS,False,82,19730,3456,7398,0.467,1268,3456,0.367,2188,3942,0.555,1238,1534,0.807,1025,2777,3802,2021,585,410,1014,1562,9418
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,3071,6933,0.443,1073,3152,0.340,1998,3781,0.528,1471,1885,0.780,847,2378,3225,2050,653,350,1292,1728,8686

=== nba_stats/Games.csv — 73,278 rows x 23 cols (11 MB) ===
columns: ['gameId', 'gameDateTimeEst', 'hometeamCity', 'hometeamName', 'hometeamId', 'awayteamCity', 'awayteamName', 'awayteamId', 'homeScore', 'awayScore', 'winner', 'gameType', 'gameSubtype', 'gameLabel', 'gameSubLabel', 'seriesGameNumber', 'attendance', 'arenaId', 'arenaName', 'arenaCity', 'arenaState', 'officials', 'gameDate']

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,winner,gameType,gameSubtype,gameLabel,gameSubLabel,seriesGameNumber,attendance,arenaId,arenaName,arenaCity,arenaState,officials,gameDate
0,42500404,2026-06-10 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,107,106,1610612752,Playoffs,NaN,NBA Finals,Game 4,Game 4,19812,30,Madison Square Garden,New York,NY,"Courtney Kirkland, Zach Zarba, James Williams,...",2026-06-10 20:30:00
1,42500403,2026-06-08 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,111,115,1610612759,Playoffs,NaN,NBA Finals,Game 3,Game 3,19812,30,Madison Square Garden,New York,NY,"Marc Davis, John Goble, Curtis Blair, Nick Buc...",2026-06-08 20:30:00
2,42500402,2026-06-05 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,104,105,1610612752,Playoffs,NaN,NBA Finals,Game 2,Game 2,19014,1000118,Frost Bank Center,San Antonio,TX,"Tony Brothers, Josh Tiven, Mitchell Ervin, Tyl...",2026-06-05 20:30:00

=== nba_stats/LeagueSchedule24_25.csv — 1,408 rows x 15 cols (0 MB) ===
columns: ['gameId', 'gameDateTimeEst', 'gameDay', 'arenaCity', 'arenaState', 'arenaName', 'gameLabel', 'gameSubLabel', 'gameSubtype', 'gameSequence', 'seriesGameNumber', 'seriesText', 'weekNumber', 'hometeamId', 'awayteamId']

,gameId,gameDateTimeEst,gameDay,arenaCity,arenaState,arenaName,gameLabel,gameSubLabel,gameSubtype,gameSequence,seriesGameNumber,seriesText,weekNumber,hometeamId,awayteamId
0,12400001,2024-10-04 12:00:00+00:00,Fri,Abu Dhabi,NaN,Etihad Arena,Preseason,NBA Abu Dhabi Game,Global Games,1,NaN,Neutral Site,0,1610612743,1610612738
1,12400002,2024-10-04 21:00:00+00:00,Fri,Salt Lake City,UT,Delta Center,Preseason,NaN,NaN,2,NaN,NaN,0,1610612762,15020
2,12400003,2024-10-04 22:30:00+00:00,Fri,Palm Desert,CA,Acrisure Arena,Preseason,NaN,NaN,3,NaN,NaN,0,1610612747,1610612750

=== nba_stats/LeagueSchedule25_26.csv — 1,400 rows x 17 cols (0 MB) ===
columns: ['gameId', 'gameDateTimeEst', 'gameDay', 'homeTeamId', 'awayTeamId', 'homeTeamName', 'homeTeamCity', 'awayTeamName', 'awayTeamCity', 'arenaName', 'arenaCity', 'arenaState', 'gameLabel', 'gameSubLabel', 'gameSubtype', 'seriesGameNumber', 'weekNumber']

,gameId,gameDateTimeEst,gameDay,homeTeamId,awayTeamId,homeTeamName,homeTeamCity,awayTeamName,awayTeamCity,arenaName,arenaCity,arenaState,gameLabel,gameSubLabel,gameSubtype,seriesGameNumber,weekNumber
0,42500405,2026-06-13 20:30:00,Sat,1610612759,1610612752,Spurs,San Antonio,Knicks,New York,Frost Bank Center,San Antonio,TX,NBA Finals,Game 5,NaN,Game 5,34
1,42500404,2026-06-10 20:30:00,Wed,1610612752,1610612759,Knicks,New York,Spurs,San Antonio,Madison Square Garden,New York,NY,NBA Finals,Game 4,NaN,Game 4,34
2,42500403,2026-06-08 20:30:00,Mon,1610612752,1610612759,Knicks,New York,Spurs,San Antonio,Madison Square Garden,New York,NY,NBA Finals,Game 3,NaN,Game 3,34

=== nba_stats/PlayByPlay.parquet — 18,726,649 rows x 89 cols (933 MB) ===
columns: ['clock', 'actionType', 'description', 'playerFullName', 'teamTricode', 'gameId', 'gameDateTimeEst', 'periodType', 'period', 'shortFormattedClock', 'timeActual', 'actionNumber', 'orderNumber', 'actionId', 'teamId', 'side', 'location', 'playerteamCity', 'playerteamName', 'opponentteamCity', 'opponentteamName', 'scoreHome', 'scoreAway', 'possession', 'isTargetScoreLastPeriod']

,clock,actionType,description,playerFullName,teamTricode,gameId,gameDateTimeEst,periodType,period,shortFormattedClock,timeActual,actionNumber,orderNumber,actionId,teamId,side,location,playerteamCity,playerteamName,opponentteamCity,...,jumpBallRecoveredPersonId,jumpBallRecoveredFullName,jumpBallWonPersonId,jumpBallWonFullName,jumpBallWonPlayerName,jumpBallLostPersonId,jumpBallLostFullName,jumpBallLostPlayerName,subsInPersonId,subsInFullName,subsInPlayerName,officialId,videoAvailable,personIdsFilter,gameType,playerteamId,opponentteamId,jumpBallRecoverdPersonId,gameDateTimeEst_g,gameType_g
0,PT12M00.00S,period,Period Start,None,None,42500151,2026-04-19 21:00:00,REGULAR,1,None,2026-04-20T01:17:50.1Z,2,20000,NaN,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None,None,None,None,[],None,None,None,None,None,None
1,PT11M56.00S,jumpball,Jump Ball V. Wembanyama vs. D. Clingan: Tip to...,Julian Champagnie,SAS,42500151,2026-04-19 21:00:00,REGULAR,1,None,2026-04-20T01:17:52.7Z,4,40000,NaN,1610612759,None,None,San Antonio,Spurs,Portland,...,None,None,1641705,Victor Wembanyama,Wembanyama,1642270,Donovan Clingan,Clingan,None,None,None,None,None,"[1630577, 1641705, 1642270]",None,None,None,None,None,None
2,PT11M37.00S,2pt,MISS V. Wembanyama driving Layup,Victor Wembanyama,SAS,42500151,2026-04-19 21:00:00,REGULAR,1,None,2026-04-20T01:18:12.6Z,7,70000,NaN,1610612759,right,None,San Antonio,Spurs,Portland,...,None,None,None,None,None,None,None,None,None,None,None,None,None,[1641705],None,None,None,None,None,None

=== nba_stats/PlayerStatistics.csv — 1,669,892 rows x 40 cols (390 MB) ===
columns: ['firstName', 'lastName', 'personId', 'gameId', 'gameDateTimeEst', 'playerteamCity', 'playerteamName', 'opponentteamCity', 'opponentteamName', 'gameType', 'gameLabel', 'gameSubLabel', 'seriesGameNumber', 'win', 'home', 'numMinutes', 'points', 'assists', 'blocks', 'steals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersAttempted', 'threePointersMade']

,firstName,lastName,personId,gameId,gameDateTimeEst,playerteamCity,playerteamName,opponentteamCity,opponentteamName,gameType,gameLabel,gameSubLabel,seriesGameNumber,win,home,numMinutes,points,assists,blocks,steals,fieldGoalsAttempted,fieldGoalsMade,fieldGoalsPercentage,threePointersAttempted,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints,playerteamId,opponentteamId,comment,startingPosition,gameDate
0,OG,Anunoby,1628384,42500404,2026-06-10 20:30:00,New York,Knicks,San Antonio,Spurs,Playoffs,NBA Finals,Game 4,4,1,1,41.466667,33,1,1,1,15,10,0.667,9,7,0.778,6,6,1.0,3,1,4,2,1,-1,1610612752,1610612759,NaN,F,2026-06-10 20:30:00
1,Landry,Shamet,1629013,42500404,2026-06-10 20:30:00,New York,Knicks,San Antonio,Spurs,Playoffs,NBA Finals,Game 4,4,1,1,20.500000,0,1,0,0,3,0,0.000,2,0,0.000,0,0,0.0,2,0,2,1,0,-13,1610612752,1610612759,NaN,NaN,2026-06-10 20:30:00
2,Bismack,Biyombo,202687,42500404,2026-06-10 20:30:00,San Antonio,Spurs,New York,Knicks,Playoffs,NBA Finals,Game 4,4,0,0,NaN,0,0,0,0,0,0,0.000,0,0,0.000,0,0,0.0,0,0,0,0,0,0,1610612759,1610612752,DNP - Coach's Decision,NaN,2026-06-10 20:30:00

=== nba_stats/PlayerStatisticsExtended.csv — 838,782 rows x 110 cols (453 MB) ===
columns: ['firstName', 'lastName', 'personId', 'gameId', 'gameDateTimeEst', 'gameType', 'gameLabel', 'gameSubLabel', 'seriesGameNumber', 'win', 'home', 'playerteamId', 'playerteamCity', 'playerteamName', 'opponentteamId', 'opponentteamCity', 'opponentteamName', 'comment', 'startingPosition', 'numMinutes', 'points', 'assists', 'reboundsTotal', 'reboundsOffensive', 'reboundsDefensive']

,firstName,lastName,personId,gameId,gameDateTimeEst,gameType,gameLabel,gameSubLabel,seriesGameNumber,win,home,playerteamId,playerteamCity,playerteamName,opponentteamId,opponentteamCity,opponentteamName,comment,startingPosition,numMinutes,...,percentUnassisted3PointMade,percentAssistedFieldGoalsMade,percentUnassistedFieldGoalsMade,percentTeamFieldGoalsMade,percentTeamFieldGoalsAttempted,percentTeamThreePointersMade,percentTeamThreePointersAttempted,percentTeamFreeThrowsMade,percentTeamFreeThrowsAttempted,percentTeamOffensiveRebounds,percentTeamDefensiveRebounds,percentTeamRebounds,percentTeamAssists,percentTeamTurnovers,percentTeamSteals,percentTeamBlocks,percentTeamBlocksAgainst,percentTeamFoulsPersonal,percentTeamFoulsDrawn,percentTeamPoints
0,Jordan,Clarkson,203903,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4,1,1,1610612752,New York,Knicks,1610612759,San Antonio,Spurs,NaN,NaN,4.666667,...,0.0,1.0,0.0,0.333,0.429,0.000,0.500,0.000,0.000,0.000,0.25,0.200,0.0,0.667,0.000,0.0,0.0,0.750,0.0,0.286
1,Devin,Vassell,1630170,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4,0,0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,NaN,F,40.350000,...,0.0,1.0,0.0,0.207,0.129,0.417,0.229,0.067,0.059,0.125,0.16,0.152,0.2,0.091,0.111,0.0,0.0,0.111,0.0,0.212
2,Carter,Bryant,1642868,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4,0,0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,NaN,NaN,5.000000,...,0.0,1.0,0.0,0.333,0.300,0.200,0.125,0.000,0.000,0.000,0.50,0.500,0.0,0.000,0.500,0.0,0.0,0.250,0.0,0.278

=== nba_stats/Players.csv — 6,692 rows x 20 cols (1 MB) ===
columns: ['personId', 'firstName', 'lastName', 'birthDate', 'school', 'country', 'heightInches', 'bodyWeightLbs', 'jersey', 'guard', 'forward', 'center', 'dleagueFlag', 'nbaFlag', 'gamesPlayedFlag', 'draftYear', 'draftRound', 'draftNumber', 'fromYear', 'toYear']

,personId,firstName,lastName,birthDate,school,country,heightInches,bodyWeightLbs,jersey,guard,forward,center,dleagueFlag,nbaFlag,gamesPlayedFlag,draftYear,draftRound,draftNumber,fromYear,toYear
0,196294534,Alberto,Abalde,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,76001,Alaa,Abdelnaby,1968-06-24,Duke,USA,82.0,240.0,30.0,0,1,0,0.0,1.0,1.0,1990.0,1.0,25.0,1990.0,1994.0
2,76002,Zaid,Abdul-Aziz,1946-04-07,Iowa State,USA,81.0,235.0,54.0,0,0,1,0.0,1.0,1.0,1968.0,1.0,5.0,1968.0,1977.0

=== nba_stats/TeamHistories.csv — 140 rows x 7 cols (0 MB) ===
columns: ['teamId', 'teamCity', 'teamName', 'teamAbbrev', 'seasonFounded', 'seasonActiveTill', 'league']

,teamId,teamCity,teamName,teamAbbrev,seasonFounded,seasonActiveTill,league
0,1610612737,Tri-Cities,Blackhawks,TRI,1946,1948,BAA
1,1610612737,Milwaukee,Hawks,MIL,1951,1954,NBA
2,1610612737,St. Louis,Hawks,STL,1955,1967,NBA

=== nba_stats/TeamStatistics.csv — 146,558 rows x 59 cols (36 MB) ===
columns: ['gameId', 'gameDateTimeEst', 'teamCity', 'teamName', 'teamId', 'opponentTeamCity', 'opponentTeamName', 'opponentTeamId', 'home', 'win', 'teamScore', 'opponentScore', 'assists', 'blocks', 'steals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersAttempted', 'threePointersMade', 'threePointersPercentage', 'freeThrowsAttempted', 'freeThrowsMade', 'freeThrowsPercentage', 'reboundsDefensive']

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,teamScore,opponentScore,assists,blocks,steals,fieldGoalsAttempted,fieldGoalsMade,fieldGoalsPercentage,threePointersAttempted,threePointersMade,...,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,coachId,gameType,gameLabel,gameSubLabel,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate
0,42500404,2026-06-10 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,0,0,106,107,24,4,10,86,36,0.419,43,17,...,12,25,28,10,2,0,1,3,NaN,Playoffs,NBA Finals,Game 4,4,2,8,1,NaN,NaN,NaN,2026-06-10 20:30:00
1,42500404,2026-06-10 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,1,1,107,106,23,4,6,78,36,0.462,32,15,...,13,11,34,14,2,0,3,1,NaN,Playoffs,NBA Finals,Game 4,4,3,14,2,NaN,NaN,NaN,2026-06-10 20:30:00
2,42500403,2026-06-08 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,1,0,111,115,18,6,4,88,40,0.455,37,13,...,15,7,46,21,4,0,2,1,NaN,Playoffs,NBA Finals,Game 3,3,3,10,0,NaN,NaN,NaN,2026-06-08 20:30:00

=== nba_stats/TeamStatisticsExtended.csv — 79,722 rows x 104 cols (38 MB) ===
columns: ['gameId', 'gameDateTimeEst', 'gameType', 'gameLabel', 'gameSubLabel', 'seriesGameNumber', 'teamId', 'teamCity', 'teamName', 'opponentTeamId', 'opponentTeamCity', 'opponentTeamName', 'home', 'win', 'teamScore', 'opponentScore', 'seed', 'numMinutes', 'assists', 'steals', 'blocks', 'blocksAgainst', 'fieldGoalsMade', 'fieldGoalsAttempted', 'fieldGoalsPercentage']

,gameId,gameDateTimeEst,gameType,gameLabel,gameSubLabel,seriesGameNumber,teamId,teamCity,teamName,opponentTeamId,opponentTeamCity,opponentTeamName,home,win,teamScore,opponentScore,seed,numMinutes,assists,steals,...,percentFieldGoalAttempts2Point,percentFieldGoalAttempts3Point,percentPoints2Point,percentPoints2PointMidRange,percentPoints3Point,percentPointsFastBreak,percentPointsFreeThrow,percentPointsOffTurnovers,percentPointsInPaint,percentAssisted2PointMade,percentUnassisted2PointMade,percentAssisted3PointMade,percentUnassisted3PointMade,percentAssistedFieldGoalsMade,percentUnassistedFieldGoalsMade,freeThrowAttemptRate,opponentEffectiveFieldGoalPercentage,opponentFreeThrowAttemptRate,opponentTurnoverPercentage,opponentOffensiveReboundPercentage
0,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,0,0,106,107,2,240.0,24,10,...,0.500,0.500,0.358,0.094,0.481,0.113,0.160,0.236,0.264,0.421,0.579,0.941,0.059,0.667,0.333,0.233,0.558,0.359,0.161,0.283
1,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4,1610612752,New York,Knicks,1610612759,San Antonio,Spurs,1,1,107,106,3,240.0,23,6,...,0.590,0.410,0.393,0.075,0.421,0.121,0.187,0.103,0.318,0.381,0.619,1.000,0.000,0.639,0.361,0.359,0.517,0.233,0.128,0.308
2,42500403,2026-06-08 20:30:00,Playoffs,NBA Finals,Game 3,3,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,0,1,115,111,2,240.0,28,7,...,0.595,0.405,0.470,0.087,0.313,0.043,0.217,0.183,0.383,0.630,0.370,0.917,0.083,0.718,0.282,0.381,0.528,0.250,0.140,0.373

## 3. Data inventory

Everything gathered so far, across live snapshots and raw dumps.

In [9]:
data.data_inventory()

     kind                                               file  size_mb
0   cache                  game_log_2025_26_playoffs.parquet     0.02
1   cache            game_log_2025_26_regular_season.parquet     0.09
2   cache       team_stats_2025_26_playoffs_advanced.parquet     0.03
3   cache  team_stats_2025_26_regular_season_advanced.par...     0.03
4   cache     team_stats_2025_26_regular_season_base.parquet     0.04
5     raw                           nba_dataset/Advanced.csv     4.63
6     raw                nba_dataset/All-Star Selections.csv     0.09
7     raw                 nba_dataset/Draft Pick History.csv     0.45
8     raw       nba_dataset/End of Season Teams (Voting).csv     0.32
9     raw                nba_dataset/End of Season Teams.csv     0.11
10    raw        nba_dataset/Opponent Stats Per 100 Poss.csv     0.22
11    raw            nba_dataset/Opponent Stats Per Game.csv     0.27
12    raw                    nba_dataset/Opponent Totals.csv     0.27
13    raw                       nba_dataset/Per 100 Poss.csv     4.23
14    raw                     nba_dataset/Per 36 Minutes.csv     4.59
15    raw                nba_dataset/Player Award Shares.csv     0.21
16    raw                 nba_dataset/Player Career Info.csv     0.51
17    raw                    nba_dataset/Player Per Game.csv     4.69
18    raw                nba_dataset/Player Play By Play.csv     1.78
19    raw                 nba_dataset/Player Season Info.csv     1.48
20    raw                    nba_dataset/Player Shooting.csv     2.87
21    raw                      nba_dataset/Player Totals.csv     4.49
22    raw                        nba_dataset/Team Abbrev.csv     0.06
23    raw            nba_dataset/Team Stats Per 100 Poss.csv     0.22
24    raw                nba_dataset/Team Stats Per Game.csv     0.28
25    raw                     nba_dataset/Team Summaries.csv     0.33
26    raw                        nba_dataset/Team Totals.csv     0.28
27    raw                                nba_stats/Games.csv    11.21
28    raw                  nba_stats/LeagueSchedule24_25.csv     0.15
29    raw                  nba_stats/LeagueSchedule25_26.csv     0.19
30    raw                       nba_stats/PlayByPlay.parquet   932.87
31    raw                     nba_stats/PlayerStatistics.csv   389.66
32    raw             nba_stats/PlayerStatisticsExtended.csv   453.31
33    raw                              nba_stats/Players.csv     0.52
34    raw                        nba_stats/TeamHistories.csv     0.01
35    raw                       nba_stats/TeamStatistics.csv    36.02
36    raw               nba_stats/TeamStatisticsExtended.csv    38.19

## Next steps

1. Download the Kaggle dumps into `data/raw/` and re-run section 2.
2. **02_features**: derive per-game series context (game number, series score, elimination flags, rest days) from the historical games table; era-normalize team strength (1980s pace ≠ 2020s pace); aggregate player box scores into availability/star-performance features.
3. **03_model**: train the series-aware win-probability model, score game 5/6/7, and Monte-Carlo the rest of the series.